fix: finalchain destructions
Taraxa-project/taraxa-node pull request #1177
Opened 2021-09-23 11:11 UTC by mfrankovi

Check that final chain thread is stopped before destroying objects

2021-09-23 11:23 UTC, MatusKysel approved these changes

2021-09-23 13:07 UTC, JakubFornadel reviewed
Nice. I think you can even delete these timeouts, which are not necessary anymore:

https://github.com/Taraxa-project/taraxa-node/blob/develop/tests/network_test.cpp#L195
https://github.com/Taraxa-project/taraxa-node/blob/develop/tests/full_node_test.cpp#L1140

2021-09-23 15:13 UTC, JakubFornadel requested changes
See my comment

2021-09-23 16:10 UTC, mfrankovi commented
> Nice. I think you can even delete these timeouts, which are not necessary anymore:
> 
> https://github.com/Taraxa-project/taraxa-node/blob/develop/tests/network_test.cpp#L195
> https://github.com/Taraxa-project/taraxa-node/blob/develop/tests/full_node_test.cpp#L1140

Deleted the timeouts and tests seem to pass fine

2021-09-24 01:01 UTC, gaoqi8649 approved these changes

2021-09-24 07:55 UTC, JakubFornadel approved these changes

2021-09-24 07:58 UTC, JakubFornadel approved these changes

2021-09-24 08:36 UTC, merged

2021-09-24 08:37 UTC, taraxadeploy commented
prnet cleaned-up successfully