chore(syncing): change condition to restart syncing
Taraxa-project/taraxa-node pull request #1266
Opened 2021-11-10 13:14 UTC by MatusKysel

## Purpose

Start syncing even if we are just one block behind

2021-11-11 00:52 UTC, gaoqi8649 requested changes
The design because we hit PBFT syncing blocks too often issue in previous time.
@justinsnapp and I discussed when trigger PBFT syncing dependent on peers status packet:
1. Only trigger restartSyncingPbft when node behind at least 2 blocks. When node just behind one block, will trigger PBFT syncing in PBFT manager.
2. When node behind more than 6 blocks, will trigger syncing in force

2021-11-11 08:09 UTC, MatusKysel commented
> The design because we hit PBFT syncing blocks too often issue in previous time. @justinsnapp and I discussed when trigger PBFT syncing dependent on peers status packet:
> 
>     1. Only trigger restartSyncingPbft when node behind at least 2 blocks. When node just behind one block, will trigger PBFT syncing in PBFT manager.
> 
>     2. When node behind more than 6 blocks, will trigger syncing in force

force syncing does not work like that, it should not be used there. I have change condition back

2021-11-11 09:00 UTC, JakubFornadel approved these changes

2021-11-11 20:15 UTC, gaoqi8649 approved these changes

2021-11-15 09:40 UTC, merged

2021-11-15 09:41 UTC, taraxadeploy commented
prnet cleaned-up successfully