Revert "chore(votes): change parameters for propose_block vote"
Taraxa-project/taraxa-node pull request #1342
Opened 2021-12-13 16:36 UTC by MatusKysel

This reverts commit c005bfacdaa6fa208d7625dc63cb8065040e0c33.

2021-12-13 22:54 UTC, gaoqi8649 approved these changes

2021-12-14 00:46 UTC, gaoqi8649 requested changes
As @justinsnapp request, I add a proposal committee size for PBFT proposal votes/blocks.
https://github.com/Taraxa-project/taraxa-node/pull/1343
I think we don't need revert it

2021-12-15 14:33 UTC, justinsnapp commented
> As @justinsnapp request, I add a proposal committee size for PBFT proposal votes/blocks. #1343 I think we don't need revert it

Why would that mean we don't need to revert this change?

2021-12-15 16:44 UTC, gaoqi8649 commented
> > As @justinsnapp request, I add a proposal committee size for PBFT proposal votes/blocks. #1343 I think we don't need revert it
> 
> Why would that mean we don't need to revert this change?

Because @MatusKysel change to do sortition for proposal PBFT votes/blocks base on total voters instead of total votes. And in https://github.com/Taraxa-project/taraxa-node/pull/1343, I add a proposal committee size as 200. That means the committee size is 200 for proposal state, and for other states the committee size is still 1000

2021-12-16 09:13 UTC, JakubFornadel approved these changes

2021-12-16 16:08 UTC, closed without merging