fix: race condition in retrieving blocks with transactions
Taraxa-project/taraxa-node pull request #1423
Opened 2022-01-17 14:59 UTC by mfrankovi

When processing a getDagSyncPacket non finalized blocks are sent only with unique set of transactions that are not finalized or included in a previous DAG block. Other transactions should already be present on the peer requesting it.

There was a race condition where it was possible that between requesting dag blocks with getNonFinalizedBlocks and transactions with db_->getNonfinalizedTransactions(trx_to_query), some blocks were actually finalized which would lead to sending some missing transactions in the packet. This has been fixed that now blocks and transactions are retrieved with a new method DagManager::getNonFinalizedBlocksWithTransactions which ensures that blocks are retrieved under the DagManager mutex which ensures that blocks cannot be finalized while retrieving this data.

2022-01-18 00:09 UTC, gaoqi8649 approved these changes

2022-01-19 11:48 UTC, JakubFornadel requested changes
So I was thinkg about this race condition for quite som time and I think I might have more elegant solution:

The problem is that between calls to blks = getNonFinalizedBlocks and db_->getNonfinalizedTransactions(trx_to_query) some of the non-finalized "blks" were finalized so getNonfinalizedTransactions did not return txs included in "blks", right ?

How about we send in getDagSyncPacket also peer's pbft period. When you receive such requets, you can check peer_period:
- if the difference between peer_period and our period is > 1/2/???, there is no need to even send him non-finalized dag blocks as he is behind and should receive pbft sync block...
- if the difference is <= 1/2/2??? we will proceed in sending him nonfinalized dag blocks
- now inside db->getNonfinalizedTransactions wee look for txs in Columns::transactions column, if we dont find it there(due to race condition), we can lookup up transaction period index and if the tx is saved in a period >= peer_period, we will retrieve it and send it

This way, there is no need for any excessive locking and it should solve this rare race-condition by retrieving few txs from period-data

2022-01-19 12:27 UTC, mfrankovi commented
> So I was thinkg about this race condition for quite som time and I think I might have more elegant solution:
> 
> The problem is that between calls to blks = getNonFinalizedBlocks and db_->getNonfinalizedTransactions(trx_to_query) some of the non-finalized "blks" were finalized so getNonfinalizedTransactions did not return txs included in "blks", right ?
> 
> How about we send in getDagSyncPacket also peer's pbft period. When you receive such requets, you can check peer_period:
> 
> * if the difference between peer_period and our period is > 1/2/???, there is no need to even send him non-finalized dag blocks as he is behind and should receive pbft sync block...
> * if the difference is <= 1/2/2??? we will proceed in sending him nonfinalized dag blocks
> * now inside db->getNonfinalizedTransactions wee look for txs in Columns::transactions column, if we dont find it there(due to race condition), we can lookup up transaction period index and if the tx is saved in a period >= peer_period, we will retrieve it and send it
> 
> This way, there is no need for any excessive locking and it should solve this rare race-condition by retrieving few txs from period-data

So the problem that I see with your approach is that you say "if we don't find it there", is that you don't know if you have found them or not. You are not looking for some specific set of transactions. I am looking only for nonfinalized transactions, not all transactions. If your idea is that we always look for all transactions(the exception would be if all transactions are non finalized) also in transaction period index I believe that this can hurt performance more than the locking but I guess it would have to be checked.

2022-01-19 18:59 UTC, gaoqi8649 commented on libraries/core_libs/consensus/src/dag/dag.cpp
> +  return {period_, std::move(dag_blocks), std::move(transactions)};
I think don't need "transactions" here. 
return {period_, std::move(dag_blocks), std::move(trxs)};

2022-01-19 19:02 UTC, gaoqi8649 commented on libraries/core_libs/network/src/tarcap/packets_handlers/get_dag_sync_packet_handler.cpp
> +    blocks.clear();
Does it need transactions clear also?

2022-01-20 13:26 UTC, JakubFornadel approved these changes

2022-01-20 14:09 UTC, MatusKysel approved these changes

2022-01-21 09:38 UTC, mfrankovi commented on libraries/core_libs/consensus/src/dag/dag.cpp
> +  return {period_, std::move(dag_blocks), std::move(transactions)};
Fixed

2022-01-21 09:41 UTC, mfrankovi commented on libraries/core_libs/network/src/tarcap/packets_handlers/get_dag_sync_packet_handler.cpp
> +    blocks.clear();
Fixed

2022-01-21 10:24 UTC, merged

2022-01-21 10:25 UTC, taraxadeploy commented
prnet cleaned-up successfully