chore: fix selection unit test in probability
Taraxa-project/taraxa-node pull request #1555
Opened 2022-02-18 20:17 UTC by gaoqi8649

Fix https://github.com/Taraxa-project/taraxa-node/issues/1554 

Fix the PBFT proposed blocks leader selection unit test with specific VRF keys and nodes voting power. Also change testing rounds from 1000 to 100, reduce the unit test running time to 2s.

2022-02-21 11:09 UTC, MatusKysel commented
did you run it at least 100x ?

2022-02-22 00:21 UTC, gaoqi8649 commented
> 



> did you run it at least 100x ?

I modify the unit test with specific VRF keys and nodes voting power. So every time running result should be exactly the same.

2022-02-22 01:19 UTC, JakubFornadel approved these changes

2022-02-22 07:43 UTC, MatusKysel commented
> > 
> 
> > did you run it at least 100x ?
> 
> I modify the unit test with specific VRF keys and nodes voting power. So every time running result should be exactly the same.

What is the meaning of this test then? we everything is fixed what we are testing?

2022-02-22 08:41 UTC, mfrankovi approved these changes

2022-02-22 08:51 UTC, MatusKysel requested changes
What is the meaning of this test then? we everything is fixed what we are testing?

2022-02-22 17:06 UTC, gaoqi8649 commented
> What is the meaning of this test then? we everything is fixed what we are testing?

I think the purpose of unit tests are fixed inputs and test exactly output. 
If PBFT selection changed(include binomial distribution, hashing, leader selection), that will effect the output. Then we will known if the change is correct or not

2022-02-23 16:29 UTC, closed without merging