fix: use u256 for transaction nonce value
Taraxa-project/taraxa-node pull request #1583
Opened 2022-02-25 23:19 UTC by gaoqi8649

Fix https://github.com/Taraxa-project/taraxa-node/issues/1558

2022-02-28 08:59 UTC, MatusKysel requested changes
This is not enough, you need to change also EVM part

2022-02-28 23:23 UTC, JakubFornadel approved these changes

2022-03-01 00:17 UTC, gaoqi8649 commented
> This is not enough, you need to change also EVM part

Fix in EVM, please review https://github.com/Taraxa-project/taraxa-evm/pull/36/

2022-03-02 11:28 UTC, MatusKysel approved these changes

2022-03-02 11:57 UTC, merged

2022-03-02 11:58 UTC, taraxadeploy commented
prnet cleaned-up successfully