V1.0.1 conflict
Taraxa-project/taraxa-node pull request #1638
Opened 2022-03-18 08:53 UTC by MatusKysel

## Purpose
Intermediary branch to resolve conflict between master v1.0.1 and develop after that we could merge https://github.com/Taraxa-project/taraxa-node/pull/1637

## How does the solution address the problem

## Changes made

2022-03-18 23:50 UTC, gaoqi8649 approved these changes

2022-03-23 09:35 UTC, JakubFornadel approved these changes

2022-03-23 09:37 UTC, JakubFornadel requested changes
Why are there 2 PR's with the same functionality ? https://github.com/Taraxa-project/taraxa-node/pull/1637

2022-03-23 09:51 UTC, MatusKysel commented
> Why are there 2 PR's with the same functionality ? #1637

as we can not change master branch, I had to create this branch and resolve conflicts. But before that I have had created branch 1637 as I did not know where are that many conflict there. If we merge this one 1637 should automatically close itself as the  code will be the same as from this one. I think this is the flow we should use as we can track it back

2022-03-23 11:49 UTC, mfrankovi approved these changes

2022-03-23 12:26 UTC, JakubFornadel approved these changes

2022-03-23 13:41 UTC, merged