chore: try to enable all tests
Taraxa-project/taraxa-node pull request #1797
Opened 2022-06-08 15:58 UTC by MatusKysel

## Purpose

## How does the solution address the problem

## Changes made

2022-06-08 21:10 UTC, gaoqi8649 approved these changes

2022-06-09 09:04 UTC, kstdl requested changes
changes in taraxa-evm isn't merged yet

2022-06-09 10:24 UTC, kstdl approved these changes

2022-06-09 11:00 UTC, merged

2022-06-09 11:02 UTC, taraxadeploy commented
prnet cleaned-up successfully