draft: final_chain cache
Taraxa-project/taraxa-node pull request #2011
Opened 2022-09-08 19:07 UTC by kstdl

#1896

2022-09-14 10:16 UTC, kstdl commented on libraries/core_libs/consensus/include/final_chain/final_chain.hpp
> +  virtual std::shared_ptr<BlockHeader> block_header(std::optional<EthBlockNumber> n = {}) const = 0;
Added const to caches where it makes sense

2022-09-14 10:16 UTC, kstdl commented on libraries/core_libs/consensus/include/final_chain/cache.hpp
> +      data_by_block_.erase(data_by_block_.begin());
This method is unused, removed it

2022-09-14 14:10 UTC, kstdl commented on libraries/core_libs/consensus/include/final_chain/cache.hpp
> +      data_by_block_.erase(data_by_block_.begin());
But it is protected already. Or am I missing something?

2022-09-14 15:32 UTC, JakubFornadel commented on libraries/core_libs/consensus/include/final_chain/cache.hpp
> +  MapByBlockCache(uint64_t blocks_to_save, GetterFn getter_fn)
GetterFn&& ?

2022-09-14 15:53 UTC, JakubFornadel commented on libraries/core_libs/consensus/src/final_chain/final_chain.cpp
> +                                [this](uint64_t blk, const addr_t& addr) { return get_dpos_is_eligible(blk, addr); }) {
what do we need this get_dpos_is_elogible function ? cannot we use here directly return state_api_.dpos_is_eligible(blk_num, addr) ?

2022-09-14 15:59 UTC, JakubFornadel requested changes
I dont see the changes related to deleting the current "cache" we are using. After this proper cache is used, we should be able to completely get rid of:

- size_t getDposTotalVotesCount() const;
- size_t getDposWeightedVotesCount() const
- uint64_t getCurrentPbftSortitionThreshold(PbftVoteTypes vote_type) const;
- potentially also other functions and variables they work with

so we celan the code little bit and we use only getters with specified period ?

Also pls look for TODO[1896] and remove it

2022-09-15 10:01 UTC, kstdl commented on libraries/core_libs/consensus/include/final_chain/cache.hpp
> +      data_by_block_.erase(data_by_block_.begin());
lock was wrongly placed in `MapByBlockCache::get`. Should protect also call of find. Fixed

2022-09-15 15:35 UTC, merged

2022-09-15 15:36 UTC, taraxadeploy commented
prnet cleaned-up successfully