Adding GH Action to Trigger build on master branch
Taraxa-project/taraxa-node pull request #837
Opened 2021-06-03 12:16 UTC by agrebin

## Purpose

Enable Triggering circleci builds con commits to master.

## For reviewers

## Related Github issues

## Changes

## Tests

## Deployment Considerations

## Version Notes ##
{ major | minor | patch }

**NOTE: Include the version notes in the squash commit message**

2021-06-03 13:46 UTC, rattrap requested changes

2021-06-03 13:46 UTC, rattrap commented on .github/workflows/trigger-ci-on-branch.yml
> +        -d "{\"branch\":\"${CIRCLE_BRANCH}\",\"pull_request\":\"${PR}\"}" \
Don't see a `PR` env var here.

2021-06-04 13:06 UTC, JakubFornadel commented on .github/workflows/trigger-ci-on-branch.yml
> +     - master
reminder, change this to testnet branch before merging....

2021-06-09 17:00 UTC, rattrap approved these changes

2021-06-09 17:11 UTC, sfrique approved these changes

2021-06-10 11:37 UTC, merged