chore(build): install clang-format/tidy in dockerfile, use proper ver…
Taraxa-project/taraxa-node pull request #879
Opened 2021-06-16 12:35 UTC by JakubFornadel

…sion

## Purpose

## For reviewers

## Related Github issues

## Changes

## Tests

## Deployment Considerations

## Version Notes ##
{ major | minor | patch }

**NOTE: Include the version notes in the squash commit message**

2021-06-16 12:55 UTC, rattrap requested changes

2021-06-16 12:55 UTC, rattrap commented on .clang-format
> +ColumnLimit:     80
ColumnLimit should be 120

2021-06-16 12:55 UTC, rattrap commented on Dockerfile
> +    apt-get install -y clang-format-$LLVM_VERSION clang-tidy-$LLVM_VERSION && \
Move this to the "# Install standard tools" section

2021-06-16 12:55 UTC, rattrap commented on CMakeModules/clang_tidy.cmake
>  if (APPLE)
No need to have this condition for APPLE. We can just keep the "else" find

2021-06-17 00:32 UTC, gaoqi8649 commented on .clang-format
> +# BasedOnStyle:  Google
Why not just use Google style?

2021-06-17 00:32 UTC, gaoqi8649 commented on src/util/timer.hpp
> +}  // namespace taraxa::util
Is this for test only? I don't find where dose use it

2021-06-17 07:29 UTC, JakubFornadel commented
> Please also build at MacOS in CircleCI, make sure that also works for Mac. Thanks!

Agree, not ewlwvant comment for any PR though. This is rather a request for @agrebin @rattrap

2021-06-17 11:26 UTC, JakubFornadel commented
> Don't forget to change add LLVM_VERSION here also:
> 
> ```
> RUN conan remote add -f bincrafters "https://api.bintray.com/conan/bincrafters/public-conan" && \
>     conan profile new clang --detect && \
>     conan profile update settings.compiler=clang clang && \
>     conan profile update settings.compiler.version=10 clang && \
>     conan profile update settings.compiler.libcxx=libstdc++11 clang && \
>     conan profile update env.CC=clang-10 clang && \
>     conan profile update env.CXX=clang++-10 clang && \
>     conan install -if $BUILD_OUTPUT_DIR --build missing -s build_type=Debug -pr=clang .
> ```

done

2021-06-17 13:32 UTC, rattrap approved these changes

2021-06-17 16:51 UTC, justinsnapp approved these changes

2021-06-17 17:13 UTC, gaoqi8649 approved these changes

2021-06-17 17:57 UTC, merged