chore(new): replace new to make_shared/unique where possible
Taraxa-project/taraxa-node pull request #997
Opened 2021-07-22 12:18 UTC by MatusKysel

## Purpose

resolves https://github.com/Taraxa-project/taraxa-node/issues/753

2021-07-22 16:30 UTC, justinsnapp approved these changes

2021-07-23 00:13 UTC, gaoqi8649 approved these changes

2021-07-23 07:30 UTC, JakubFornadel commented
so why not to delete s_ptr and u_ptr functions here ?

2021-07-23 07:31 UTC, JakubFornadel requested changes
so why not to delete s_ptr and u_ptr functions here ?

2021-07-23 08:12 UTC, JakubFornadel approved these changes

2021-07-23 08:52 UTC, merged